### ISSUE TITLE
maven artifact signing issue

### ISSUE THREAD

**Issue by AdrianCozma** [kaazing/java.client#21]
I'm getting an error when trying to push a component to artifactory:

[INFO] --- maven-gpg-plugin:1.5:sign (default) @ test.release.java.client ---
gpg: no default secret key: No secret key
gpg: signing failed: No secret key
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:23 min
[INFO] Finished at: 2015-06-24T12:16:32+00:00
[INFO] Final Memory: 21M/51M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.5:sign (default) on project test.release.java.client: Exit code: 2 -> [Help 1]

We need to update jenkins with the credentials key.  This is blocking the CE java client and gateway QA release stories

**Comment by ahousing** [comment]
I know nothing about the maven-gpg-plugin.  Do we have any internal documentation on using this plugin?  For example, a google doc explaining our new build process.  Even a transaction for when this requirement was added?

**Comment by ahousing** [comment]
Also, I need an environment to investigate.  Where/how is this running?  (Email me the answer.)  Kris emailed that "Configuring GPG in Maven's settings.xml" needed to have the password hard-coded in it.  I would need to look at this file to see what we have.
    BTW, that also comes back to the initial plan of using this plugin.  Do we have a plan for not having a plain-text password in a file?  I searched my email for maven-gpg-plugin and can't find anything.  I'm thinking a spec would be helpful

**Comment by ahousing** [comment]
Private details posted in private issue [issues #2](https://github.com/kaazing/issues/issues/2)
