### ISSUE TITLE
Travis CI is broken

### ISSUE THREAD

**Issue by dpwspoon** [kaazing/java.client#40]
https://github.com/kaazing/java.client/pull/39/files

**Comment by Anisotrop** [comment]
The failing build: https://travis-ci.org/kaazing/java.client/builds/224465687

**Comment by zahariaca** [comment]
I have run the build locally and it builds successfully. Will discuss with QA if this is a Travis issue.

**Comment by zahariaca** [comment]
The PR has been merged. Closing issue.
