### ISSUE TITLE
 Integrate RabbitMQ Messaging doc link is broken

### ISSUE THREAD

**Issue by akrambek** [kaazing/java.client#6]
If you click on  Integrate RabbitMQ Messaging doc link in  https://github.com/kaazing/java.client/blob/develop/amqp-0-9-1/doc/o_dev_java_amqp.md.  It redirects you into this page https://github.com/kaazing/java.client/blob/develop/amqp-0-9-1/integration-amqp/p_amqp_integrate_rabbitmq.md which is broken.

**Comment by vjwang** [comment]
PR: https://github.com/kaazing/java.client/pull/28
