### ISSUE TITLE
Ubuntu / Java 8 Build error

### ISSUE THREAD

**Issue by AdrianCozma** [kaazing/java.client#7]
I tried to build this repo but ran into some problems, basically it fails on some tests.
I ran the command from the readme(mvn clean install) on an ubuntu 14.04 VM with Java 1.8.0_45 and maven 3.0.5 while connected to the Kaazing VPN.
Please advise on this matter(I am not sure if this is a bug or if I am missing any settings).
Below you can find the console output describing the problem.

Results :

Tests in error: 
  testRequestReady(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): unexpected invocation
  testRequestClosed(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testRequestLoaded(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testRequestProgressed(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessOpen(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testErrorOccured(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessOpenWithProtocol(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testRequestAborted(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessOpenWithMultipleProtocols(org.kaazing.gateway.client.impl.wseb.CreateHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testExtendedHandshakeWith401(org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessConnect(org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testExtendedHandshakeFailed(org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessAuthorize(org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testExtendedHandshakeSuccess(org.kaazing.gateway.client.impl.wsn.WebSocketNativeHandshakeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessAuthorizeWithoutChallengeHandler(org.kaazing.gateway.client.impl.wsn.WebSocketNativeAuthenticationHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessConnect(org.kaazing.gateway.client.impl.wsn.WebSocketNativeAuthenticationHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessAuthorizeWithChallengeHandler(org.kaazing.gateway.client.impl.wsn.WebSocketNativeAuthenticationHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessBalancerMessage(org.kaazing.gateway.client.impl.wsn.WebSocketNativeBalancingHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessBinaryMessage(org.kaazing.gateway.client.impl.wsn.WebSocketNativeBalancingHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessTextMessage(org.kaazing.gateway.client.impl.wsn.WebSocketNativeBalancingHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testProcessBalancerRedirectMessage(org.kaazing.gateway.client.impl.wsn.WebSocketNativeBalancingHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testWssFallback(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testJavaWseSsl(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testJavaWseFailed(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testInvalidScheme(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Unexpected exception, expected<java.net.URISyntaxException> but was<java.lang.NoClassDefFoundError>
  testJavaWsFailed(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testWsFallback(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testJavaWs(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testJavaWse(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testJavaWss(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler
  testWseFallback(org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandlerTest): Could not initialize class org.kaazing.gateway.client.impl.ws.WebSocketCompositeHandler

Tests run: 247, Failures: 0, Errors: 31, Skipped: 3

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Kaazing Java Clients .............................. SUCCESS [4.325s]
[INFO] Kaazing Java Client - Net API ..................... SUCCESS [3.299s]
[INFO] Kaazing Java Client - Transport ................... SUCCESS [14.346s]
[INFO] Kaazing Java Client - Bridge ...................... SUCCESS [3.498s]
[INFO] Kaazing Java Client - WebSocket Common ............ SUCCESS [0.160s]
[INFO] Kaazing Java Client - WebSocket RFC-6455 .......... FAILURE [28.660s]
[INFO] Kaazing Java Client - WebSocket Demo .............. SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Common ........... SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Library .......... SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Demo ............. SKIPPED
[INFO] Kaazing Java Client - API Documentation ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 55.008s
[INFO] Finished at: Fri May 22 18:01:30 EEST 2015
[INFO] Final Memory: 56M/136M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.10:test (default-test) on project gateway.client.java: There are test failures.

**Comment by sanjay-saxena** [comment]
Hey Adrian -- Can you please make sure that you are using the correct(32-bit vs 64-bit) version of JDK 8?

**Comment by sanjay-saxena** [comment]
I did the build on an Ubuntu box with JDK 8 and here are the results:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Kaazing Java Clients .............................. SUCCESS [19.158s]
[INFO] Kaazing Java Client - Net API ..................... SUCCESS [4.073s]
[INFO] Kaazing Java Client - Transport ................... SUCCESS [12.435s]
[INFO] Kaazing Java Client - Bridge ...................... SUCCESS [2.060s]
[INFO] Kaazing Java Client - WebSocket Common ............ SUCCESS [0.033s]
[INFO] Kaazing Java Client - WebSocket RFC-6455 .......... SUCCESS [1:04.557s]
[INFO] Kaazing Java Client - WebSocket Demo .............. SUCCESS [5.271s]
[INFO] Kaazing Java Client - AMQP 0-9-1 Common ........... SUCCESS [0.070s]
[INFO] Kaazing Java Client - AMQP 0-9-1 Library .......... SUCCESS [2.322s]
[INFO] Kaazing Java Client - AMQP 0-9-1 Demo ............. SUCCESS [1.669s]
[INFO] Kaazing Java Client - API Documentation ........... SUCCESS [33.256s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:27.387s
[INFO] Finished at: Fri May 22 15:24:09 PDT 2015
[INFO] Final Memory: 84M/503M
[INFO] ------------------------------------------------------------------------
build@qabuilder:~/tmp/java.client$ uname -a
Linux qabuilder 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
build@qabuilder:~/tmp/java.client$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

**Comment by AdrianCozma** [comment]
hi sanjay,
i checked the java version and it is the proper one(64 bit)
icozma@icozma-VirtualBox:~$ uname -a
Linux icozma-VirtualBox 3.16.0-37-generic #51~14.04.1-Ubuntu SMP Wed May 6 15:23:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
icozma@icozma-VirtualBox:~$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

I managed to get a build success when skipping the tests(ran the command "mvn clean install -DskipTests -DskipITs") and after I can run the demo clients successfully(with the commands from the readme).
If i run just "mvn clean install" I get the same error as in the previous comment.
I also tried to build it on my Windows 7 machine(also with java 8) and again it only works when skipping the tests, though here it fails when trying to execute an IT.

below is the output for Windows 7

Running org.kaazing.gateway.client.impl.ws.WebSocketIT
line 1:12 token recognition error at: '\b'
line 1:24 token recognition error at: '\b'
line 1:12 token recognition error at: '\b'
line 1:24 token recognition error at: '\b'
May 25, 2015 12:41:43 PM org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader run2
SEVERE: java.net.SocketException: Unexpected end of file from server
May 25, 2015 12:41:43 PM org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader run
INFO: WebSocket upstream channel already closed
java.lang.IllegalStateException: WebSocket upstream channel already closed
        at org.kaazing.gateway.client.impl.wseb.WebSocketEmulatedHandler$2.upstreamFailed(WebSocketEmulatedHandler.java:134)
        at org.kaazing.gateway.client.impl.wseb.UpstreamHandlerImpl$3.errorOccurred(UpstreamHandlerImpl.java:131)
        at org.kaazing.gateway.client.impl.http.HttpRequestTransportHandler$2.errorOccurred(HttpRequestTransportHandler.java:100)
        at org.kaazing.gateway.client.impl.http.HttpRequestDelegateHandler$1.errorOccurred(HttpRequestDelegateHandler.java:139)
        at org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader.run2(HttpRequestDelegateImpl.java:270)
        at org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader.run(HttpRequestDelegateImpl.java:224)
        at java.lang.Thread.run(Thread.java:745)

May 25, 2015 12:41:43 PM org.kaazing.gateway.client.transport.http.HttpRequestDelegateImpl$StreamReader run2
SEVERE: java.net.SocketException: Unexpected end of file from server
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.363 sec <<< FAILURE! - in org.kaazing.gateway.client.impl.ws.WebSocketIT
clientShouldReceiveDataOverLongpollingRequest(org.kaazing.gateway.client.impl.ws.WebSocketIT)  Time elapsed: 10.082 sec  <<< FAILURE!
org.junit.ComparisonFailure: Specified behavior did not match expected:<...M_REQUEST_RECEIVED

[write await LONG_POLLING_REQUEST_RECEIVED
write status "200" "OK"
write version "HTTP/1.1"
write header "Content-Type" "application/octet-stream"
write header "Connection" "close"

write [0x01 0x30 0x31 0xFF]
write close
write notify DOWNSTREAM_CLOSED

 Overlapping Downstream (Longpolling)
accept http://localhost:8001/echo/;e/dbm/NMLBn6kH9nyesgt34tOvDai9EmdrGYSI?.ki=p
accepted
connected

read await DOWNSTREAM_REQUEST_RECEIVED
read method "POST"
read version "HTTP/1.1"
read header "X-Sequence-No" ${wse:asString(sequence + 2)}
read closed
read notify LONG_POLLING_REQUEST_RECEIVED

write await DOWNSTREAM_CLOSED
write status "200" "OK"
write version "HTTP/1.1"
write header "Content-Type" "application/octet-stream"
write header content-length

write [0x81 0x11]
write "Hello, WebSocket!"
write [0x01 0x30 0x32 0xFF]
write [0x01 0x30 0x31 0xFF]
write close]
> but was:<...M_REQUEST_RECEIVED

[

 Overlapping Downstream (Longpolling)
accept http://localhost:8001/echo/;e/dbm/NMLBn6kH9nyesgt34tOvDai9EmdrGYSI?.ki=p
accepted
connected

read await DOWNSTREAM_REQUEST_RECEIVED
read method "POST"
read version "HTTP/1.1"
read header "X-Sequence-No" ${wse:asString(sequence + 2)}
read ...]
>
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at org.kaazing.net.impl.util.BlockingQueueImpl.take(BlockingQueueImpl.java:115)
        at org.kaazing.net.ws.impl.io.WsMessageReaderImpl.next(WsMessageReaderImpl.java:123)
        at org.kaazing.gateway.client.impl.ws.WebSocketIT.clientShouldReceiveDataOverLongpollingRequest(WebSocketIT.java:205)


Results :

Failed tests:
  WebSocketIT.clientShouldReceiveDataOverLongpollingRequest Specified behavior did not match expected:<...M_REQUEST_RECEIVED

[write await LONG_POLLING_REQUEST_RECEIVED
write status "200" "OK"
write version "HTTP/1.1"
write header "Content-Type" "application/octet-stream"
write header "Connection" "close"

write [0x01 0x30 0x31 0xFF]
write close
write notify DOWNSTREAM_CLOSED

 Overlapping Downstream (Longpolling)
accept http://localhost:8001/echo/;e/dbm/NMLBn6kH9nyesgt34tOvDai9EmdrGYSI?.ki=p
accepted
connected

read await DOWNSTREAM_REQUEST_RECEIVED
read method "POST"
read version "HTTP/1.1"
read header "X-Sequence-No" ${wse:asString(sequence + 2)}
read closed
read notify LONG_POLLING_REQUEST_RECEIVED

write await DOWNSTREAM_CLOSED
write status "200" "OK"
write version "HTTP/1.1"
write header "Content-Type" "application/octet-stream"
write header content-length

write [0x81 0x11]
write "Hello, WebSocket!"
write [0x01 0x30 0x32 0xFF]
write [0x01 0x30 0x31 0xFF]
write close]
> but was:<...M_REQUEST_RECEIVED

[

 Overlapping Downstream (Longpolling)
accept http://localhost:8001/echo/;e/dbm/NMLBn6kH9nyesgt34tOvDai9EmdrGYSI?.ki=p
accepted
connected

read await DOWNSTREAM_REQUEST_RECEIVED
read method "POST"
read version "HTTP/1.1"
read header "X-Sequence-No" ${wse:asString(sequence + 2)}
read ...]
>

Tests run: 5, Failures: 1, Errors: 0, Skipped: 0

[INFO]
[INFO] --- k3po-maven-plugin:2.0.0:stop (default) @ gateway.client.java ---
[INFO]
[INFO] >>> maven-source-plugin:2.4:jar (attach-sources) > generate-sources @ gateway.client.java >>>
[INFO]
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-override) @ gateway.client.java ---
[INFO] Skipping Rule Enforcement.
[INFO]
[INFO] --- license-maven-plugin:1.0.0.11:verify-notice (default) @ gateway.client.java ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.13:check (default) @ gateway.client.java ---
[INFO]
[INFO] --- maven-dependency-plugin:2.8:unpack (unpack) @ gateway.client.java ---
[INFO] Configured Artifact: org.kaazing:community.license:?:jar
[INFO] Unpacking C:\Users\icozma.ROMANIA\.m2\repository\org\kaazing\community.license\1.2\community.license-1.2.jar to C:\Users\icozma.ROMANIA\Documents\GitHub\java.client.sanjay\ws\ws\target\dependency with includes "" and excludes ""
[INFO]
[INFO] <<< maven-source-plugin:2.4:jar (attach-sources) < generate-sources @ gateway.client.java <<<
[INFO]
[INFO] --- maven-source-plugin:2.4:jar (attach-sources) @ gateway.client.java ---
[INFO] Building jar: C:\Users\icozma.ROMANIA\Documents\GitHub\java.client.sanjay\ws\ws\target\gateway.client.java-develop-SNAPSHOT-sources.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.18.1:verify (default) @ gateway.client.java ---
[INFO] Failsafe report directory: C:\Users\icozma.ROMANIA\Documents\GitHub\java.client.sanjay\ws\ws\target\failsafe-reports
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Kaazing Java Clients ............................... SUCCESS [  2.337 s]
[INFO] Kaazing Java Client - Net API ...................... SUCCESS [  1.745 s]
[INFO] Kaazing Java Client - Transport .................... SUCCESS [  5.673 s]
[INFO] Kaazing Java Client - Bridge ....................... SUCCESS [  1.005 s]
[INFO] Kaazing Java Client - WebSocket Common ............. SUCCESS [  0.100 s]
[INFO] Kaazing Java Client - WebSocket RFC-6455 ........... FAILURE [ 43.576 s]
[INFO] Kaazing Java Client - WebSocket Demo ............... SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Common ............ SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Library ........... SKIPPED
[INFO] Kaazing Java Client - AMQP 0-9-1 Demo .............. SKIPPED
[INFO] Kaazing Java Client - API Documentation ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 54.858 s
[INFO] Finished at: 2015-05-25T12:41:44+03:00
[INFO] Final Memory: 35M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:verify (default) on project gateway.client.java: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\icozma.ROMANIA\Documents\GitHub\java.client.sanjay\ws\ws\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :gateway.client.java

**Comment by AdrianCozma** [comment]
I ran "mvn clean install" a few more times on Windows 7 and sometimes I get a build success but on Ubuntu I still get the error mentioned in the first comment

**Comment by sanjay-saxena** [comment]
Hey Adrian -- WebSocketIT. clientShouldReceiveDataOverLongpollingRequest() failure on Windows 7 under JDK 8 is tracked by issue #8. I have a pull-request for that issue.

It's not clear why `mvn clean install` is resulting in `Could not initialize class` on Linux with JDK 8.

**Comment by sanjay-saxena** [comment]
I just tried this on a Docker machine that was created using Ubuntu 14.04.2, JDK 8, and Maven 3.1.3 and java.client built successfully. Here are the docker machine details:

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
```
```
# uname -a
Linux 3591deb096bc 4.0.3-boot2docker #1 SMP Wed May 13 20:54:49 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
Note that the docker machine has JDK 1.8.0_40(instead of 1.8.0_45):
```
# java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

Note that the docker machine has Maven 3.3.1(instead of 3.0.5):
```
# mvn -version
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T20:10:27+00:00)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.0.3-boot2docker", arch: "amd64", family: "unix"
```
Here is the Docker file that I used:
```
# This is a comment
FROM jbbarquero/ubuntu-java8_oracle-maven
MAINTAINER Javier Beneito Barquero <jbbarquero@gmail.com>
RUN apt-get update && apt-get install -y git
```
Here are the steps assuming that you have `docker`(and maybe `boot2docker`, if needed) already setup on your machine:

- Create Dockerfile using the aforementioned contents.
- `docker build -t jbbarquero/ubuntu-java8_oracle-maven-git  .`
- `docker run -t -i jbbarquero/ubuntu-java8_oracle-maven-git /bin/bash`
- `cd /tmp`
- `git clone https://github.com/kaazing/java.client.git`
- `cd java.client`
- `mvn clean install`

If you like, you can also create a docker image that uses Ubuntu 14.04.02, JDK 1.8.0_45, and Maven 3.0.5 and repeat the aforementioned steps.

**Comment by sanjay-saxena** [comment]
If you are having trouble with creating a docker-based env, then you can do the following once you sign into VPN:

- `ssh build@build-linux-1.kaazing.test`
- Enter the password from `Autonomous Build (Build Machines)` spreadsheet
- `cd /tmp`
- `git clone https://github.com/kaazing/java.client.git`
- `cd java.client`
- `mvn clean install`

**Comment by AdrianCozma** [comment]
Hi Sanjay,

Regarding the issue I had in Ubuntu with some of the unit tests failing, it seems the problem was with the order in which the tests were run(this run order was different in Windows and Ubuntu, hence the different build status), namely in Ubuntu the test: "org.kaazing.gateway.client.impl.wseb.WebSocketEmulatedHandlerTest" ran first and because of this some of the other tests failed; the reason for this was that this test is overriding some static variables(namely createHandlerFactory, upstreamHandlerFactory and downstreamHandlerFactory) and this is causing some other tests(like the tests in the "CreateHandlerTest" class) to fail; 
Adding the lines:
>WebSocketEmulatedHandler.createHandlerFactory = CreateHandlerImpl.FACTORY;
   WebSocketEmulatedHandler.upstreamHandlerFactory = UpstreamHandlerImpl.FACTORY;
   WebSocketEmulatedHandler.downstreamHandlerFactory = DownstreamHandlerImpl.FACTORY;

at the end of both tests in the "WebSocketEmulatedHandlerTest" class(testProcessOpen and testProcessFailed) fixes this problem(after adding these lines the project built successfully on my ubuntu image).

I forked the java.client repo, added this fix to it and will create a pull request for this.

I also tried building on a docker image as per your instructions but got the same error; also after applying the same fix as above the build was successful.

**Comment by sanjay-saxena** [comment]
Hi Adrian -- Did you try running on **build-linux-1.kaazing.test**? I had provided steps above.

**Comment by AdrianCozma** [comment]
I haven't tried, but i can try now before going home.
Can you please send me a link to the Autonomous Build (Build Machines) spreadsheet and also provide access?

**Comment by sanjay-saxena** [comment]
Can you also send me you email address so that I can add you as a contact in my IM?

**Comment by AdrianCozma** [comment]
adrian.cozma.luxoft@gmail.com

**Comment by sanjay-saxena** [comment]
My [fork](https://github.com/sanjay-saxena/java.client) contains the changes to WebSocketEmulatedHandlerTest along the lines that you have suggested but slightly different. You can clone my fork an see if it builds on your Ubuntu configuration.
